name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
          ANDROID_HOME: $ {{ env.ANDROID_HOME }}

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: app-debug-apk
          path: app/build/output/apk/debug/app-debug-apk
